### ISSUE TITLE
bug: Softwrap is not effective

### ISSUE THREAD

**Issue by rhandy-mathflow** [thisissandipp/typethis#6]
## 🐞 Bug

First, thank you for this package :)

**Description**

Softwrap is not effective for a RichText in a Row

**To Reproduce**

1. Add ThisThis like this:
```
        TypeThis(
            string: 'This is my super text and it is too long for the mobile screen width',
          ),
```
2. See "A RenderFlex overflowed..." exception

**Expected behavior**

Have an effective softWrap

**Operating System:**
Android emulator
Android 14.0 (API 34)

Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (7 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

**Solution**

Use an Expanded widget around the RichText inside the Row

**Comment by justsandip** [comment]
Thanks for opening this bug.

I see what you are saying. But it's going to be tricky to have an Expanded widget around RichText, and the reason is it will push the BlinkingCusrsor towards the right end, which is not ideal. I'm looking for solutions to have this fixed.

**Comment by rhandy-mathflow** [comment]
Maybe just with a Flexible instead of an Expanded ?

**Comment by justsandip** [comment]
Isn't that going to keep the Blinking Cursor to the right end after the text reaches the next line?
